<?php

namespace App\Repository;

/**
 * ConfigNumCasoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigNumCasoRepository extends \Doctrine\ORM\EntityRepository
{

    public function getLastNumeroCaso($anio, $mes, $em) {
        $qb = $this->createQueryBuilder('m');
           $qb->andWhere('m.anio = :anio')
           ->andWhere('m.mes = :mes')
           ->setParameter(':anio', $anio)
           ->setParameter(':mes', $mes);
        $query = $qb->getQuery();
        $r = $query->getResult();
        
        if(!empty($r)){
            
			$em->refresh($query->getSingleResult());
				
			$sr = $query->getSingleResult();
			$ultimonumero = $sr->getUltimonumero();
			
			$qb2 = $this->createQueryBuilder('m');  
			$qb2->update()
					->set('m.ultimonumero', $qb2->expr()->literal($ultimonumero + 1))
					->where('m.anio = :anio')
					->andWhere('m.mes = :mes')
					->setParameter(':anio', $anio)
					->setParameter(':mes', $mes)
					->getQuery()->execute();
			
			$em->refresh($sr);
			
			$qb3 = $this->createQueryBuilder('m');
			$qb3->andWhere('m.anio = :anio')
				->andWhere('m.mes = :mes')
				->setParameter(':anio', $anio)
				->setParameter(':mes', $mes);
			$query3 = $qb3->getQuery();
			$sr2 = $query3->getSingleResult();
			$ultimonumero1 = $sr2->getUltimonumero();
			
				 
			return  $ultimonumero1;  
        
        }else{
            return false;
        }      
        
    }
    
}