# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    application_tools.type.dependent_filtered_entity:
        public: true
        class: App\Application\ToolsBundle\Form\Type\DependentFilteredEntityType
        arguments: ["@doctrine", "@property_accessor"]
        tags:
            - { name: form.type, alias: apptools_dependent_filtered_entity }
       
    application_tools.dependent_filtered_entity_subscriber:
        public: true
        class: App\Application\ToolsBundle\Form\EventListener\DependentFilteredEntitySubscriber
        arguments: ["@property_accessor"]
        tags:
            - { name: form.type, alias: apptools_dependent_filtered_entity_subscriber } 

    admin.color:
        class: App\Admin\ColorAdmin
        arguments: [~, App\Entity\Color, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Info. General, label: Color }
        public: true

    admin.motivo:
        class: App\Admin\MotivoAdmin
        arguments: [~, App\Entity\Motivo, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Info. General, label: Motivo }
        public: true

    admin.marca:
        class: App\Admin\MarcaAdmin
        arguments: [~, App\Entity\Marca, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Info. General, label: Marca }
        public: true

    admin.modelo:
        class: App\Admin\ModeloAdmin
        arguments: [~, App\Entity\Modelo, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Info. General, label: Modelo }
        public: true

    admin.provincia:
        class: App\Admin\ProvinciaAdmin
        arguments: [~, App\Entity\Provincia, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Info. General, label: Provincia }
        public: true

    admin.localidad:
        class: App\Admin\LocalidadAdmin
        arguments: [~, App\Entity\Localidad, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Info. General, label: Localidad }
        public: true

    admin.falla:
        class: App\Admin\FallaAdmin
        arguments: [~, App\Entity\Falla, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Info. General, label: Falla }
        public: true

    admin.distancia:
        class: App\Admin\DistanciaAdmin
        arguments: [~, App\Entity\Distancia, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Info. General, label: Distancia }
        public: true

    admin.empresa:
        class: App\Admin\EmpresaAdmin
        arguments: [~, App\Entity\Empresa, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Empresas, label: Empresas, icon: '<i class="fa fa-suitcase"></i>' }
        public: true		

    admin.cliente:
        class: App\Admin\ClienteAdmin
        arguments: [~, App\Entity\Cliente, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Empresas, label: Clientes }
        public: true

    admin.servicio:
        class: App\Admin\ServicioAdmin
        arguments: [~, App\Entity\Servicio, ~]
        calls:
            - [setTemplate, ['edit', '\ServicioAdmin\edit.html.twig']]
            - [setTemplate, ['list', '\ServicioAdmin\base_list.html.twig']]
            - [ addChild, ["@admin.servicio_movil"]] 
        tags:
            - { name: sonata.admin, manager_type: orm, group: Servicios, label: Servicios pendientes, icon: '<i class="fa fa-truck"></i>' }
        public: true

    admin.tiposervicio:
        class: App\Admin\TiposervicioAdmin
        arguments: [~, App\Entity\Tiposervicio, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Servicios, label: Tipo Servicio }
        public: true

    admin.tipo_cliente:
        class: App\Admin\TipoclienteAdmin
        arguments: [~, App\Entity\Tipocliente, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Servicios, label: Tipo Cliente }
        public: true

    admin.tipoestado:
        class: App\Admin\TipoestadoAdmin
        arguments: [~, App\Entity\Tipoestado, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Servicios, label: Tipo Estado }
        public: true

    admin.chofer:
        class: App\Admin\ChoferAdmin
        arguments: [~, App\Entity\Chofer, App\Controller\ChoferAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Servicios, label: Chofer, icon: '<i class="fa fa-database"></i>' }
        public: true

    admin.movil:
        class: App\Admin\MovilAdmin
        arguments: [~, App\Entity\Movil, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Servicios, label: Movil }
        public: true
        
    my.serviciosubscriber:
        class: App\EventListener\ServicioSubscriber
        #arguments: ["@doctrine.orm.entity_manager", @service_container]
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    admin.prioridad:
        class: App\Admin\PrioridadAdmin
        arguments: [~, App\Entity\Prioridad, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Info. General, label: Prioridad }
        public: true

    admin.servicio_movil:
        class: App\Admin\ServicioMovilAdmin
        arguments: [~, App\Entity\ServicioMovil, App\Controller\ServicioMovilAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: ServicioMovil }
        public: true
